T_base_link__camera_front:
  cols: 4
  data:
  - '-0.001'
  - '-0.011'
  - '1.000'
  - '0.132'
  - '-1.000'
  - '0.001'
  - '-0.001'
  - '-0.002'
  - '-0.001'
  - '-1.000'
  - '-0.011'
  - '0.350'
  - '0.000'
  - '0.000'
  - '0.000'
  - '1.000'
  rows: 4
T_base_link__camera_left:
  cols: 4
  data:
  - '0.951'
  - '-0.006'
  - '0.309'
  - '0.104'
  - '-0.309'
  - '0.001'
  - '0.951'
  - '0.040'
  - '-0.006'
  - '-1.000'
  - '-0.001'
  - '0.351'
  - '0.000'
  - '0.000'
  - '0.000'
  - '1.000'
  rows: 4
T_base_link__camera_rear_left:
  cols: 4
  data:
  - '0.589'
  - '-0.001'
  - '-0.808'
  - '0.057'
  - '0.808'
  - '-0.004'
  - '0.589'
  - '0.026'
  - '-0.004'
  - '-1.000'
  - '-0.002'
  - '0.351'
  - '0.000'
  - '0.000'
  - '0.000'
  - '1.000'
  rows: 4
T_base_link__camera_rear_right:
  cols: 4
  data:
  - '-0.588'
  - '0.001'
  - '-0.809'
  - '0.055'
  - '0.809'
  - '-0.000'
  - '-0.588'
  - '-0.023'
  - '-0.001'
  - '-1.000'
  - '-0.001'
  - '0.350'
  - '0.000'
  - '0.000'
  - '0.000'
  - '1.000'
  rows: 4
T_base_link__camera_right:
  cols: 4
  data:
  - '-0.951'
  - '-0.001'
  - '0.310'
  - '0.101'
  - '-0.310'
  - '0.001'
  - '-0.951'
  - '-0.041'
  - '0.001'
  - '-1.000'
  - '-0.001'
  - '0.350'
  - '0.000'
  - '0.000'
  - '0.000'
  - '1.000'
  rows: 4
T_base_link__camera_up:
  cols: 4
  data:
  - '-0.951'
  - '0.308'
  - '-0.002'
  - '0.089'
  - '-0.308'
  - '-0.951'
  - '0.003'
  - '-0.001'
  - '-0.001'
  - '0.004'
  - '1.000'
  - '0.413'
  - '0.000'
  - '0.000'
  - '0.000'
  - '1.000'
  rows: 4
T_base_link__os_sensor:
  cols: 4
  data:
  - '-0.719'
  - '0.669'
  - '0.188'
  - '0.178'
  - '-0.682'
  - '-0.732'
  - '-0.001'
  - '-0.000'
  - '0.137'
  - '-0.129'
  - '0.982'
  - '0.465'
  - '0.000'
  - '0.000'
  - '0.000'
  - '1.000'
  rows: 4
T_base_link__base_footprint:
  cols: 4
  data:
  - '1.000'
  - '0.000'
  - '0.000'
  - '0.000'
  - '0.000'
  - '1.000'
  - '0.000'
  - '0.000'
  - '0.000'
  - '0.000'
  - '1.000'
  - '-0.132'
  - '0.000'
  - '0.000'
  - '0.000'
  - '1.000'

